---
title: "Final"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: sandstone
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
---
Figures
======================================================================

Column {data-width=2}
-----------------------------------------------------------------------
### High phenolics diet 

Phenolic compounds are well known for their bioactivities and their health
outcome. in this study we fed obese and lean mice a control and a purple potato (PM) diet. after 11 weeks of diet, the liver metabolites were analyzed by using LC/MS. 
Here you see top 25 metabolites with high VIP score that are driving the separation 
of Test


```{r setup, include=FALSE}
#install.packages("showtext")
library(knitr)
library(flexdashboard)
library(tidyverse)
library(magrittr)
library(dplyr)
library(ggplot2)
library(htmlwidgets)
library(plotly)
library(forcats)
library(tidyr)
library(ggthemes)
library(ggdark)
library(viridis)
library(readr)
#library(showtext)

```

Column {data-width=5}
-----------------------------------------------------------------------
### Metabolites with higher concentration in liver

```{r, fig.width=100}
liver_vip <- read.csv("Obesedata.csv", header = TRUE)
liver_vip <- liver_vip %>% 
  select(., -1) %>% 
  slice(1:25)

vip_liverOB <- liver_vip %>% 
  mutate(Metabolite = forcats::fct_reorder(Metabolite, VIP.1)) %>% 
  ggplot(aes(x= VIP.1, y= Metabolite, color = Super.Class, text = Sub_Class)) +
  geom_point() +
  labs(x = element_blank(), y = "Metabolites") + 
  scale_fill_viridis_d() +
  dark_theme_bw()

ggplotly(vip_liverOB, tooltip = "text")

```

Column {data-width=5}
-----------------------------------------------------------------------
### immune cell 

```{r}
immunecell <- read.csv("ObeseImmune.csv")

# adding column name to the first and second column 
colnames(immunecell)[1:2] <- c("Genotype", "Diet")

# selecting for two columns
immunecell <- select(immunecell, c(Genotype, Diet, ICAM.1,P.selectin))

# making the data longer
immunecell <- immunecell %>% 
  pivot_longer (cols= (ICAM.1:P.selectin),
                            names_to = "immune_cell", 
                            values_to = "Aboundance") 
immunecell <-immunecell  %>% 
  mutate(Genotype = as.factor(Genotype),
         Diet = as.factor(Diet))

mmunecell_plot <- immunecell %>% 
  group_by(Diet) %>% 
  group_by(Genotype) %>% 
  ggplot(aes(x = immune_cell, y = Aboundance, fill = Genotype, color = Diet)) +
  geom_bar(stat = "identity", alpha = 0.9) +
  labs(x = "Immune Cell", y = "Abundance") + 
  scale_fill_viridis_d() +
  dark_theme_bw()

ggplotly(mmunecell_plot)






```


High Phenolics diet 
======================================================================  

Column {data-width=4} 
-----------------------------------------------------------------------
These data have been collected as a part of pre-clinical study on 
high phenolics diet and their effect on cardiometabolic health. 
The obesedata.csv file include the VIP score of the metabolites in the liver.  




